import type { CSSProperties } from "react";

// ---------------------------------------------------------------------------
// ERA-SPECIFIC STYLES (The "Web 2.0" Look)
// ---------------------------------------------------------------------------
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const styles: Record<string, any> = {
  body: {
    // backgroundColor: '#dcdcdc',
    // backgroundImage: 'linear-gradient(to bottom, #dcdcdc 0%, #e6e6e6 100%)',
    fontFamily: "Verdana, Geneva, sans-serif",
    // paddingBottom: '40px',
  },
  mainContainer: {
    maxWidth: "960px", // The standard width of that era
    margin: "0 auto",
    backgroundColor: "#f5f5f5",
    boxShadow: "0 0 20px rgba(0,0,0,0.5)",
    border: "1px solid #999",
    borderTop: "none",
  },
  header: {
    background: "linear-gradient(to bottom, #360621 0%, #0d2533 100%)",
    height: "120px",
    position: "relative" as const,
    borderBottom: "4px solid #ccaa00", // Gold accent common in enterprise sites
    display: "flex",
    alignItems: "center",
    paddingLeft: "30px",
    overflow: "hidden",
  },
  headerShine: {
    position: "absolute" as const,
    top: "0",
    left: "0",
    width: "100%",
    height: "50%",
    background: "linear-gradient(to bottom, rgba(255,255,255,0.15) 0%, rgba(255,255,255,0.05) 100%)",
    pointerEvents: "none" as const,
  },
  logoText: {
    color: "#ffffff",
    fontFamily: '"Trebuchet MS", Helvetica, sans-serif',
    fontSize: "42px",
    fontWeight: "bold",
    textShadow: "2px 2px 4px #000000",
    letterSpacing: "-1px",
  },
  logoSub: {
    color: "#eee",
    fontSize: "14px",
    letterSpacing: "3px",
    marginTop: "-5px",
    textTransform: "uppercase",
  },
  navBar: {
    backgroundColor: "#e0e0e0",
    background: "linear-gradient(to bottom, #f0f0f0 0%, #d0d0d0 100%)",
    borderBottom: "1px solid #bfbfbf",
    padding: "10px 20px",
    display: "flex",
    justifyContent: "center",
    gap: "10px",
    boxShadow: "inset 0 1px 0 #fff",
  },
  navButton: (isActive?: boolean): CSSProperties => ({
    padding: "8px 25px",
    borderRadius: "20px",
    fontFamily: "Arial, sans-serif",
    fontSize: "14px",
    fontWeight: "bold",
    textTransform: "uppercase",
    cursor: "pointer",
    color: isActive ? "#fff" : "#444",
    background: isActive
      ? "linear-gradient(to bottom, #360621 0%, #0d2533 100%)" // Theme color glossy
      : "linear-gradient(to bottom, #f9f9f9 0%, #e0e0e0 100%)", // Grey glossy
    border: isActive ? "1px solid #0d2533" : "1px solid #bbb",
    boxShadow: isActive ? "inset 0 1px 0 rgba(255,255,255,0.4), 0 1px 2px rgba(0,0,0,0.2)" : "0 1px 2px rgba(0,0,0,0.1)",
    textShadow: isActive ? "0 -1px 0 rgba(0,0,0,0.5)" : "0 1px 0 #fff",
  }),
  contentArea: {
    padding: "30px",
    backgroundImage: 'url("https://www.transparenttextures.com/patterns/concrete-wall.png")', // Subtle noise texture
    backgroundColor: "#eeeeee",
  },
  mainCard: {
    backgroundColor: "#ffffff",
    border: "1px solid #ccc",
    borderRadius: "15px",
    padding: "20px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.1), inset 0 0 60px rgba(0,0,0,0.02)",
    marginBottom: "20px",
    position: "relative" as const,
  },
  pageTitle: {
    textAlign: "center" as const,
    color: "#360621",
    fontSize: "28px",
    fontFamily: "Georgia, serif",
    fontWeight: "bold",
    textShadow: "1px 1px 0 #fff",
    borderBottom: "2px dotted #ccc",
    paddingBottom: "15px",
    marginBottom: "25px",
  },
  timelineContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "40px 0",
    position: "relative" as const,
  },
  timelineLine: {
    position: "absolute" as const,
    height: "4px",
    background: "#bbb",
    width: "80%",
    top: "50%",
    zIndex: 0,
    borderTop: "1px solid #999",
    borderBottom: "1px solid #fff",
  },
  timelineOrb: (isMain?: boolean): CSSProperties => ({
    width: isMain ? "120px" : "90px",
    height: isMain ? "120px" : "90px",
    borderRadius: "50%",
    background: isMain
      ? "radial-gradient(ellipse at center, #ffffff 0%, #e6f4ff 50%, #b8dfff 100%)"
      : "radial-gradient(ellipse at center, #f0f0f0 0%, #dcdcdc 100%)",
    border: isMain ? "4px solid #fff" : "3px solid #fff",
    boxShadow: "0 5px 15px rgba(0,0,0,0.2), inset 0 0 10px rgba(0,0,0,0.1)",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
    margin: "0 20px",
    color: isMain ? "#360621" : "#666",
    fontWeight: "bold",
    textAlign: "center" as const,
    position: "relative" as const,
  }),
  orbGloss: {
    position: "absolute" as const,
    top: "5%",
    left: "15%",
    width: "70%",
    height: "40%",
    background: "linear-gradient(to bottom, rgba(255,255,255,0.9) 0%, rgba(255,255,255,0) 100%)",
    borderRadius: "50%",
    zIndex: 2,
  },
  sectionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
    marginTop: "30px",
  },
  insetPanel: {
    backgroundColor: "#f2f2f2",
    border: "1px solid #d0d0d0",
    borderRadius: "8px",
    padding: "20px",
    boxShadow: "inset 0 2px 5px rgba(0,0,0,0.05)",
  },
  panelHeader: {
    color: "#360621",
    fontSize: "18px",
    fontWeight: "bold",
    borderBottom: "2px solid #0d2533",
    paddingBottom: "8px",
    marginBottom: "15px",
    textTransform: "uppercase",
  },
  techList: {
    listStyle: "none",
    padding: 0,
  },
  techItem: {
    display: "flex",
    alignItems: "center",
    marginBottom: "12px",
    color: "#555",
    fontSize: "14px",
    fontWeight: "bold",
    borderBottom: "1px solid #e0e0e0",
    paddingBottom: "5px",
  },
  iconBox: {
    width: "24px",
    height: "24px",
    marginRight: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e0e0e0",
    borderRadius: "4px",
    border: "1px solid #ccc",
    color: "#444",
  },
  footer: {
    background: "linear-gradient(to bottom, #444 0%, #222 100%)",
    padding: "15px",
    textAlign: "center" as const,
    color: "#ccc",
    fontSize: "11px",
    borderTop: "5px solid #360621",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  socialIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "28px",
    height: "28px",
    background: "linear-gradient(to bottom, #666 0%, #333 100%)",
    borderRadius: "4px",
    marginLeft: "8px",
    border: "1px solid #000",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.2)",
    color: "#fff",
    cursor: "pointer",
  },
};
